from pathlib import Path

root = Path('/home/ubuntu/prop_hunt_skybound_v1')
props = [
    ('Furniture_Chair01', -8, 0.0, -5, 0, 25, 0),
    ('Furniture_Chair02', -4, 0.0, -5, 0, -15, 0),
    ('Furniture_Couch01', 5, 0.0, -6, 0, 90, 0),
    ('Furniture_Table01', 0, 0.0, -3, 0, 20, 0),
    ('Furniture_Bookshelf01', 9, 0.0, -4, 0, -90, 0),
    ('School_chair', -9, 0.0, 2, 0, 180, 0),
    ('School_desk', -5, 0.0, 3, 0, -20, 0),
    ('School_locker', 9, 0.0, 3, 0, 0, 0),
    ('School_shelf_001', 5, 0.0, 4, 0, 180, 0),
    ('School_lamp', -1, 0.0, 6, 0, 15, 0),
    ('School_blackboardbig', 0, 0.0, -10, 0, 0, 0),
    ('School_CAFETERIAvendingmachine', 10, 0.0, 8, 0, 0, 0),
    ('School_CAFETERIApingpongtable', -7, 0.0, 9, 0, 25, 0),
    ('School_PRINCIPALOFFICEdesk', 5, 0.0, 10, 0, -10, 0),
    ('School_toiletdoor', -10, 0.0, -10, 0, 90, 0),
    ('School_toiletbasictoilet', -7, 0.0, -10, 0, 0, 0),
    ('Lab_COMPUTERpc', 3, 0.0, -8, 0, 40, 0),
    ('Lab_COMPUTERscreen', 6, 0.0, -8, 0, -20, 0),
    ('Lab_CHEMESTRYtable', 3, 0.0, 6, 0, 180, 0),
    ('Lab_CHEMISTRYmicroscope', 7, 0.0, 6, 0, 30, 0),
    ('Farm_haystackround', -11, 0.0, 7, 0, 10, 0),
    ('Farm_woodenbox', -4, 0.0, 10, 0, 0, 0),
    ('Farm_barrel', 0, 0.0, 10, 0, 45, 0),
    ('Done_Wood_Plank_A', 11, 0.0, -9, 0, 90, 0),
]
lines = ['[gd_scene load_steps=40 format=3]']
lines += [
    '[ext_resource type="Script" path="res://prop_hunt_game.gd" id="1_game"]',
    '[ext_resource type="Script" path="res://prop_hunt_player.gd" id="2_player"]',
    '[ext_resource type="PackedScene" path="res://Character.glb" id="3_character"]',
    '[ext_resource type="Script" path="res://hunter.gd" id="4_hunter"]',
]
for i, (name, *_rest) in enumerate(props):
    lines.append(f'[ext_resource type="PackedScene" path="res://props/{name}.tscn" id="prop{i}"]')
lines += [
    '[sub_resource type="BoxMesh" id="FloorMesh"]',
    'size = Vector3(28, 0.4, 28)',
    '[sub_resource type="StandardMaterial3D" id="FloorMaterial"]',
    'albedo_color = Color(0.08, 0.12, 0.18, 1)',
    'roughness = 0.86',
    '[sub_resource type="BoxShape3D" id="FloorShape"]',
    'size = Vector3(28, 0.4, 28)',
    '[sub_resource type="CapsuleMesh" id="HunterMesh"]',
    'radius = 0.42',
    'height = 1.9',
    '[sub_resource type="StandardMaterial3D" id="HunterMaterial"]',
    'albedo_color = Color(0.75, 0.08, 0.12, 1)',
    'emission_enabled = true',
    'emission = Color(0.18, 0.01, 0.01, 1)',
    '[sub_resource type="CapsuleShape3D" id="HunterShape"]',
    'radius = 0.42',
    'height = 1.9',
    '[sub_resource type="CapsuleShape3D" id="PlayerShape"]',
    'radius = 0.38',
    'height = 1.8',
    '[sub_resource type="StyleBoxFlat" id="ResultStyle"]',
    'bg_color = Color(0.02, 0.04, 0.08, 0.96)',
    'border_width_left = 2',
    'border_width_top = 2',
    'border_width_right = 2',
    'border_width_bottom = 2',
    'border_color = Color(0.3, 0.8, 1, 0.9)',
    'corner_radius_top_left = 16',
    'corner_radius_top_right = 16',
    'corner_radius_bottom_left = 16',
    'corner_radius_bottom_right = 16',
    '',
    '[node name="PropHunt" type="Node3D"]',
    'script = ExtResource("1_game")',
    '',
    '[node name="WorldEnvironment" type="WorldEnvironment" parent="."]',
    '',
    '[node name="Sun" type="DirectionalLight3D" parent="."]',
    'rotation_degrees = Vector3(-52, -28, 0)',
    'light_color = Color(0.65, 0.78, 1, 1)',
    'light_energy = 1.1',
    'shadow_enabled = true',
    '',
    '[node name="Floor" type="StaticBody3D" parent="."]',
    'collision_layer = 1',
    '[node name="Mesh" type="MeshInstance3D" parent="Floor"]',
    'mesh = SubResource("FloorMesh")',
    'material_override = SubResource("FloorMaterial")',
    'position = Vector3(0, -0.2, 0)',
    '[node name="CollisionShape3D" type="CollisionShape3D" parent="Floor"]',
    'shape = SubResource("FloorShape")',
    'position = Vector3(0, -0.2, 0)',
]
# Four low walls, just enough to define a compact search room.
for i, (pos, size) in enumerate([((0, 2, -14), (28, 4, 0.4)), ((0, 2, 14), (28, 4, 0.4)), ((-14, 2, 0), (0.4, 4, 28)), ((14, 2, 0), (0.4, 4, 28))]):
    lines += [
        f'[node name="Wall{i}" type="StaticBody3D" parent="."]',
        f'position = Vector3({pos[0]}, {pos[1]}, {pos[2]})',
        f'[node name="Collision" type="CollisionShape3D" parent="Wall{i}"]',
        f'shape = SubResource("FloorShape")',
        f'scale = Vector3({size[0]/28:.3f}, {size[1]/0.4:.3f}, {size[2]/28:.3f})',
    ]
for i, (name, x, y, z, rx, ry, rz) in enumerate(props):
    lines += [
        f'[node name="HideProp_{i:02d}_{name}" parent="." groups=["hide_props"] instance=ExtResource("prop{i}")]',
        f'position = Vector3({x:.2f}, {y:.2f}, {z:.2f})',
        f'rotation_degrees = Vector3({rx}, {ry}, {rz})',
    ]
lines += [
    '[node name="Player" type="CharacterBody3D" parent="."]',
    'position = Vector3(0, 1.2, 9)',
    'script = ExtResource("2_player")',
    '[node name="Character" parent="Player" instance=ExtResource("3_character")]',
    'rotation = Vector3(0, 3.141593, 0)',
    '[node name="CollisionShape3D" type="CollisionShape3D" parent="Player"]',
    'position = Vector3(0, 0.9, 0)',
    'shape = SubResource("PlayerShape")',
    '[node name="CameraPivot" type="Node3D" parent="Player"]',
    'position = Vector3(0, 1.2, 0)',
    '[node name="Camera3D" type="Camera3D" parent="Player/CameraPivot"]',
    'position = Vector3(0, 2.2, 6.4)',
    'current = true',
    'fov = 70.0',
    '[node name="Hunter" type="CharacterBody3D" parent="."]',
    'position = Vector3(0, 1.2, -8)',
    'script = ExtResource("4_hunter")',
    '[node name="Mesh" type="MeshInstance3D" parent="Hunter"]',
    'mesh = SubResource("HunterMesh")',
    'material_override = SubResource("HunterMaterial")',
    'position = Vector3(0, 0.95, 0)',
    '[node name="CollisionShape3D" type="CollisionShape3D" parent="Hunter"]',
    'position = Vector3(0, 0.9, 0)',
    'shape = SubResource("HunterShape")',
    '[node name="HUD" type="CanvasLayer" parent="."]',
    '[node name="Title" type="Label" parent="HUD"]',
    'offset_left = 24.0',
    'offset_top = 18.0',
    'offset_right = 600.0',
    'offset_bottom = 55.0',
    'theme_override_colors/font_color = Color(0.7, 0.9, 1, 1)',
    'theme_override_font_sizes/font_size = 26',
    'text = "PROP HUNT: KAYIP KAMPÜS"',
    '[node name="Timer" type="Label" parent="HUD"]',
    'offset_left = 24.0',
    'offset_top = 60.0',
    'offset_right = 380.0',
    'offset_bottom = 92.0',
    'theme_override_font_sizes/font_size = 22',
    'text = "KALAN SÜRE  02:00"',
    '[node name="Status" type="Label" parent="HUD"]',
    'offset_left = 24.0',
    'offset_top = 98.0',
    'offset_right = 900.0',
    'offset_bottom = 130.0',
    'theme_override_colors/font_color = Color(0.5, 1, 0.75, 1)',
    'theme_override_font_sizes/font_size = 18',
    '[node name="Hint" type="Label" parent="HUD"]',
    'offset_left = 24.0',
    'offset_top = 660.0',
    'offset_right = 1000.0',
    'offset_bottom = 700.0',
    'theme_override_colors/font_color = Color(0.72, 0.8, 0.9, 1)',
    'theme_override_font_sizes/font_size = 16',
    '[node name="ResultPanel" type="Panel" parent="HUD"]',
    'visible = false',
    'offset_left = 430.0',
    'offset_top = 240.0',
    'offset_right = 850.0',
    'offset_bottom = 470.0',
    'theme_override_styles/panel = SubResource("ResultStyle")',
    '[node name="Result" type="Label" parent="HUD/ResultPanel"]',
    'layout_mode = 1',
    'anchors_preset = 15',
    'anchor_right = 1.0',
    'anchor_bottom = 1.0',
    'grow_horizontal = 2',
    'grow_vertical = 2',
    'theme_override_colors/font_color = Color(0.9, 0.97, 1, 1)',
    'theme_override_font_sizes/font_size = 24',
    'horizontal_alignment = 1',
    'vertical_alignment = 1',
]
(root / 'main.tscn').write_text('\n'.join(lines) + '\n')
print('props', len(props), 'scene_lines', len(lines))
